### ISSUE TITLE
包名那个参数怎么处理？

### ISSUE THREAD

**Issue by YEHong1** [1556173267/react-native-apk-manager#1]
嗯。。。
react native 怎么才能够获取包名呢？

**Comment by 1556173267** [comment]
@YEHong1 你使用的是哪个方法。是 isExpChannel() 吗？这个方法是用来判断 安装apk 是否是 对应渠道过来的。 所以你需要 传入 自己期望的包名做参数。然后和APP AndroidManifest里写死的 渠道号作对比。

**Comment by YEHong1** [comment]
我想用下载apk后卸载，用uninstallApk()方法，它需要传入一个包名作为参数，但是我不知道如何取获取它

**Comment by YEHong1** [comment]
@1556173267 我下载apk后想卸载，用uninstallApk()方法，它需要传入一个包名作为参数，但是我不知道如何去获取它

**Comment by 1556173267** [comment]
你可以去 手机自带的 设置 里面的应用列表里查看。这几天我会追加一个通过下载的apk路径 获取apk包名的方法。

**Comment by YEHong1** [comment]
@1556173267 好的

**Comment by 1556173267** [comment]
新增了 getAPKInformation()  getAppInformation()  getAppMetaDataByKey() getInstalledAppInfo() 方法。 @YEHong1

**Comment by YEHong1** [comment]
@1556173267 感谢
